language: smalltalk
sudo: false

before_install:
  - sudo apt-get install libhunspell-1.3-0:i386
  - ln -s /usr/lib/i386-linux-gnu/libhunspell-1.3.so.0 libhunspell-1.3.so.0

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
